[package]
name = "certo-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.0.15", features = ["derive"]}
color-eyre = "0.6.2"
eyre = "0.6.8"
rustls = {version = "0.20.6", features = ["dangerous_configuration"]}
rustls-native-certs = "0.6.2"
rustls-pemfile = "1.0.1"
thiserror = "1.0.37"
time = "0.3.15"
webpki-roots = "0.22.5"
x509-parser = "0.14.0"
